spring:
  profiles:
    include: base
    active: base, boot

---
spring:
  profiles: boot
  datasource:
    url: jdbc:postgresql://localhost:5555/shogun?currentSchema=shogun
  flyway:
    schemas: shogun, public
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: mail.terrestris.de
    port: 587
    protocol: smtp
    username: noreply
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000

server:
  port: 8080
  servlet:
    context-path: /shogun-boot

support:
  email: noreply@terrestris.de

keycloak:
  auth-server-url: http://localhost:8000/auth
  realm: SpringBootKeycloak
  resource: shogun-app
  public-client: true
  ssl-required: external
  principal-attribute: preferred_username

jpa:
  hibernate:
    jdbc:
      lob:
        non_contextual_creation: true
    ddl-auto: sdfdsf
flyway:
  enabled: false
