spring:
  profiles:
    active: base, boot

---

spring:
  config:
    activate:
      on-profile: boot
    import: classpath:application-base.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5555/shogun?currentSchema=shogun
  messages:
    basename: org/springframework/security/messages, de/terrestris/shogun/lib/messages
  mail:
    host: mail.terrestris.de
    port: 587
    protocol: smtp
    username: noreply
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000

server:
  port: 8080
  servlet:
    context-path: /shogun-boot

support:
  email: noreply@terrestris.de

management:
  endpoints:
    web:
      exposure:
        include: "*"
